## 【問題4】目的関数
以下の数式で表されるロジスティック回帰の 目的関数（損失関数） を実装してください。そして、これをself.loss, self.val_lossに記録するようにしてください。


なお、この数式には正則化項が含まれています。


＊数式が見切れる場合、DIVERを全画面にして御覧ください。

In [1]:
def _linear_hypothesis(X, theta):
    """
    線形の仮定関数を計算する
    Parameters
    ----------
    X : 次の形のndarray, shape (n_samples, n_features)
    訓練データ
    theta : 次の形のndarray, shape (n_features, 1)
    重み

    Returns
    -------
      次の形のndarray, shape (n_samples, 1)
      線形の仮定関数による推定結果
    """

    h = 1 / (1 + np.exp(-(X @ theta.T)))

    return h 

In [15]:
def get_loss(test_X, test_y, theta):
    """
    平均二乗誤差の計算
    Parameters
    ----------
    y_pred : 次の形のndarray, shape (n_samples,)
      推定した値
    y : 次の形のndarray, shape (n_samples,)
      正解値
    theta_T
    Returns
    ----------
    mse : numpy.float
      平均二乗誤差
    """
    # LAMBDA=1と仮定
    
    h = _linear_hypothesis(test_X, theta)
    sigma_1 = (np.log(h).T @ (-1 * test_y)) - (np.log(1 - h).T @ (1 - test_y))
    sigma_2 = theta @ theta.T
    loss = 1 / h.shape[0] * sigma_1 + 0.1 / h.shape[0] * sigma_2

    return loss

In [16]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [17]:
h = np.array([[0.01, 0.1, 0.2, 0.3, 0.4]]) # 更新後と仮定
theta = np.array([[0.01, 0.1]]) # 更新後と仮定
train_X = np.array([[1, 1, 1, 1, 1], [0, 1, 2, 3, 4]]).T
test_X = np.array([[1, 1, 1, 1, 1], [5, 6, 7, 8, 9]]).T
train_y = np.array([[0, 0, 1, 1, 1]]).T
test_y = np.array([[0, 1, 0, 1, 1]]).T
loss = np.zeros((h_history.shape[0], 1))

In [18]:
loss = (np.log(h_history) @ (-1 * test_y)) - (np.log(1 - h_history) @ (1 - test_y))
loss # iteration, 1

array([[4.65604252]])

In [19]:
h = _linear_hypothesis(test_X, theta)

In [20]:
(np.log(h).T @ (-1 * test_y)) - (np.log(1 - h).T @ (1 - test_y))

array([[3.23043298]])

In [21]:
get_loss(test_X, test_y, theta)

array([[0.6462886]])